import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import Navbar from './Navbar/page';
import Footer from './Footer/page';
import { Providers } from './providers';
import { Toaster } from "@/components/ui/toaster"

const font = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Youtube STO - BAY',
  description: 'Generated by BAY',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
