import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import Navbar from '../components/navbar/page';
import Footer from '../components/footer/page';
import { Providers } from './providers';
import { Toaster } from '@/components/ui/toaster';
import Head from 'next/head';
import { auth } from '@/auth';

const font = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Youtube STO - BAY',
  description: 'Generated by BAY',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  console.log('currentUser', session);
  return (
    <html lang='en'>
      <body className={font.className}>
        <Providers>
          <Navbar currentUser={session} />
          {children}
          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
